server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://localhost:3100/loki/api/v1/push
    tenant_id: raw

scrape_configs:
  - job_name: "orders"
    static_configs:
      - targets:
          - localhost
        labels:
          job: orders
          service: orders
          environment: dev
          __path__: /.logs/orders.log*

    pipeline_stages:
      - json:
          expressions:
            level: level
            region: region
            payment_method: payment_method
            status: status
      - labels:
          region:
          payment_method:
          status:
